# Puerto del servidor Spring Boot
server.port=5000

# Desactivar la pantalla de login automática de Spring Security
# (nosotros implementamos nuestro propio login)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Mostrar logs útiles en consola durante el taller
logging.level.arep.lab08=DEBUG
